name = "equation-syntax-tree"
version = "0.1.0"
license = "license"
author = "Eelis Takala"
maintainer = "eelis.takala@gmail.com"
copyright = "Copyright 2022, Eelis Takala"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
